apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-hello-app
  namespace: default
spec:
  type: Java
  mode: cluster
  image: spark-hello-app:3.5.1  # <- Custom image you just built
  imagePullPolicy: IfNotPresent
  mainClass: com.spark.hello.app.SparkHelloAppApplication
  mainApplicationFile: 'local:///opt/spark/jars/spark-hello-app-2.7.0.jar'
  sparkVersion: "3.5.1"
  restartPolicy:
    type: Never
  sparkConf:
    spark.kubernetes.container.image.pullPolicy: IfNotPresent
    spark.kubernetes.executor.podNamePrefix: spark-hello-app-exec
    spark.kubernetes.authenticate.driver.serviceAccountName: spark-job-sa
    spark.kubernetes.api.timeout: "60000"
    spark.kubernetes.executor.uploadLocalJars: "false"
    spark.kubernetes.driver.uploadLocalJars: "false"
    spark.hadoop.fs.file.impl: org.apache.hadoop.fs.LocalFileSystem
  driver:
    cores: 2
    memory: "2g"
    labels:
      version: 1.0.0
    serviceAccount: spark-job-sa
    annotations:
      sparkoperator.k8s.io/spark-ui-port: "4040"
      sparkoperator.k8s.io/spark-ui-service-type: "NodePort"
      sparkoperator.k8s.io/spark-ui-node-port: "30400"
  executor:
    cores: 1
    instances: 1
    memory: "1g"
    labels:
      version: 1.0.0