#apiVersion: v1
#kind: Service
#metadata:
#  name: spark-ui-service
#  namespace: {{ .Values.serviceAccount.namespace }}
#spec:
#  type: NodePort
#  selector:
#    spark-role: driver
#    spark-app-selector: spark-hello-app
#  ports:
#    - name: webui
#      protocol: TCP
#      port: 4040
#      targetPort: 4040
#      nodePort: {{ .Values.driver.uiNodePort }}
