pipeline:
  name: HelloApp Pipeline
  identifier: helloapp-pipeline
  description: "Spring Boot Application CI/CD Pipeline"
  tags: []

  # Define the stages in the pipeline
  stages:
    - stage:
        name: Clone and Build
        identifier: clone_and_build
        type: Run
        spec:
          execution:
            steps:
              - step:
                  name: Clone Repository
                  type: GitClone
                  spec:
                    connectorRef: githubConnector  # GitHub connector ref
                    repositoryName: 'your_repo_name'
                    branch: 'main'

              - step:
                  name: Build with Maven
                  type: Run
                  spec:
                    command: mvn clean package
                    shell: Bash

    - stage:
        name: Build Docker Image
        identifier: build_docker
        type: Run
        spec:
          execution:
            steps:
              - step:
                  name: Build Docker Image
                  type: Run
                  spec:
                    command: |
                      docker build -t your_dockerhub_username/helloapp:${CI_COMMIT_SHA} .
                    shell: Bash

    - stage:
        name: Push Docker Image to DockerHub
        identifier: push_docker
        type: Run
        spec:
          execution:
            steps:
              - step:
                  name: Push Docker Image
                  type: Run
                  spec:
                    command: |
                      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
                      docker push your_dockerhub_username/helloapp:${CI_COMMIT_SHA}
                    shell: Bash

    - stage:
        name: Deploy to Kubernetes (Minikube)
        identifier: deploy_k8s
        type: Run
        spec:
          execution:
            steps:
              - step:
                  name: Helm Deploy
                  type: Run
                  spec:
                    command: |
                      helm upgrade --install helloapp ./helm/helloapp --set image.repository=your_dockerhub_username/helloapp --set image.tag=${CI_COMMIT_SHA}
                    shell: Bash

    - stage:
        name: Expose Application
        identifier: expose_app
        type: Run
        spec:
          execution:
            steps:
              - step:
                  name: Expose Service
                  type: Run
                  spec:
                    command: |
                      kubectl expose deployment helloapp --port=8080 --target-port=8080 --type=LoadBalancer --name=helloapp-service
                    shell: Bash
